logging:
  # "."是logback.xml中 LOG_USER LOG_PREFIX所需的默认值。其作用是当执行"java -jar xxx.jar" 没有覆盖日志路径时，默认存放在当前路径下。
  #    userpath: currentuser
  userpath: .
  #    prefixpath: logprefix
  prefixpath: .


pdd:
  clientId: ENC(fAlR/yw/3AN2HuDY2lTxr987lOYeeBrlMNWW3xN4WcONDFvRh042BRzIQVQaUI0DuurqMb60eGZyt/MlRN7cfvaAe/IppMtB4iA4Ecl4MvY=)
  clientSecret: ENC(d/gdv6vHHnVMcoLbkqcNw8HgrLrjqdap2rOuG/5OlkpRJzCu2oh/gd4BqoLADLmzSSHLlrscqlBTatfETKlDwFw7jkE0XlNzoTe8bkHS+WM=)